# Generated by Django 4.1 on 2022-08-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField(default=None)),
                ('death_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
